version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "dev"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "dev"
