name: 🚀 Feature request
description: Suggest an idea for Session
title: '[Feature] <title>'
labels: [feature-request]
body:
- type: checkboxes
  attributes:
    label: Is there an existing request for feature?
    description: Please search to see if an issue already exists for the feature you are requesting.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: What feature would you like?
    description: |
      A clear and concise description of the feature you would like added to Session
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Add any other context or screenshots about the feature request here
  validations:
    required: false
